@echo off
title Ngrok Backend Tunnel
color 0B

echo.
echo ===================================================
echo   NGROK BACKEND TUNNEL
echo   Exposes backend to the internet for mobile apps
echo ===================================================
echo.

REM Check if ngrok is installed
where ngrok >nul 2>&1
if %errorlevel% neq 0 (
    echo [ERROR] ngrok is not installed or not in PATH.
    echo.
    echo Install ngrok:
    echo   1. Download from https://ngrok.com/download
    echo   2. Unzip and add to PATH
    echo   3. Run: ngrok config add-authtoken YOUR_TOKEN
    echo.
    pause
    exit /b 1
)

echo [1/4] Starting ngrok tunnel for port 8000...
start /B ngrok http 8000 > nul 2>&1

echo [2/4] Waiting for ngrok to initialize (5 seconds)...
timeout /t 5 /nobreak > nul

echo [3/4] Fetching ngrok public URL...

REM Query ngrok API to get the public URL
for /f "tokens=*" %%i in ('powershell -Command "(Invoke-RestMethod -Uri 'http://localhost:4040/api/tunnels').tunnels[0].public_url"') do set NGROK_URL=%%i

if "%NGROK_URL%"=="" (
    echo [ERROR] Failed to get ngrok URL. Is ngrok running?
    echo Try running: ngrok http 8000
    pause
    exit /b 1
)

echo.
echo ===================================================
echo   NGROK URL: %NGROK_URL%
echo ===================================================
echo.

echo [4/4] Updating mobile/config.ts with ngrok URL...

REM Update the config file
(
echo // Backend configuration for mobile apps
echo // This file is auto-generated by start_ngrok.cmd
echo // DO NOT EDIT MANUALLY - it will be overwritten
echo.
echo // Ngrok public URL - auto-updated
echo export const BACKEND_URL = '%NGROK_URL%';
echo.
echo // WebSocket URL ^(derived from BACKEND_URL^)
echo export const WS_URL = BACKEND_URL.replace^('http', 'ws'^).replace^('https', 'wss'^) + '/ws';
) > "%~dp0mobile\config.ts"

echo.
echo [SUCCESS] Config updated!
echo.
echo Mobile apps will now connect to: %NGROK_URL%
echo.
echo ===================================================
echo   NEXT STEPS:
echo   1. Restart Expo servers (Ctrl+C then npx expo start)
echo   2. Scan QR codes with Expo Go
echo   3. Mobile apps will connect via ngrok tunnel
echo ===================================================
echo.
echo Press any key to open ngrok dashboard...
pause > nul
start http://localhost:4040
