@echo off
title Ngrok Backend Tunnel
color 0B

echo.
echo ===================================================
echo   NGROK BACKEND TUNNEL
echo   Exposes backend to the internet for mobile apps
echo ===================================================
echo.

REM Use local ngrok.exe from project folder
set NGROK_PATH=%~dp0ngrok.exe

if not exist "%NGROK_PATH%" (
    echo [ERROR] ngrok.exe not found at: %NGROK_PATH%
    echo.
    echo Download ngrok from https://ngrok.com/download
    pause
    exit /b 1
)

echo [1/5] Found ngrok at: %NGROK_PATH%

echo [2/5] Starting ngrok tunnel for port 8000...
start /B "" "%NGROK_PATH%" http 8000 > nul 2>&1

echo [3/5] Waiting for ngrok to initialize (5 seconds)...
timeout /t 5 /nobreak > nul

echo [4/5] Fetching ngrok public URL...

REM Query ngrok API to get the public URL
for /f "tokens=*" %%i in ('powershell -Command "(Invoke-RestMethod -Uri 'http://localhost:4040/api/tunnels').tunnels[0].public_url"') do set NGROK_URL=%%i

if "%NGROK_URL%"=="" (
    echo [ERROR] Failed to get ngrok URL.
    echo.
    echo Possible issues:
    echo   1. ngrok needs auth token - run: "%NGROK_PATH%" config add-authtoken YOUR_TOKEN
    echo   2. Get your token at: https://dashboard.ngrok.com/get-started/your-authtoken
    echo.
    pause
    exit /b 1
)

echo.
echo ===================================================
echo   NGROK URL: %NGROK_URL%
echo ===================================================
echo.

echo [5/5] Updating mobile app config files with ngrok URL...

REM Update BLE Advertiser config
(
echo // Backend configuration for BLE Advertiser
echo // This file is auto-generated by start_ngrok.cmd
echo // DO NOT EDIT MANUALLY - it will be overwritten
echo.
echo // Ngrok public URL - auto-updated
echo export const BACKEND_URL = '%NGROK_URL%';
echo.
echo // WebSocket URL ^(derived from BACKEND_URL^)
echo export const WS_URL = BACKEND_URL.replace^('http', 'ws'^).replace^('https', 'wss'^) + '/ws';
) > "%~dp0mobile\ble-advertiser\config.ts"

REM Update BLE Receiver config
(
echo // Backend configuration for BLE Receiver
echo // This file is auto-generated by start_ngrok.cmd
echo // DO NOT EDIT MANUALLY - it will be overwritten
echo.
echo // Ngrok public URL - auto-updated
echo export const BACKEND_URL = '%NGROK_URL%';
echo.
echo // WebSocket URL ^(derived from BACKEND_URL^)
echo export const WS_URL = BACKEND_URL.replace^('http', 'ws'^).replace^('https', 'wss'^) + '/ws';
) > "%~dp0mobile\ble-receiver\config.ts"

echo.
echo [SUCCESS] Both config files updated!
echo.
echo Mobile apps will now connect to: %NGROK_URL%
echo.
echo ===================================================
echo   NEXT STEPS:
echo   1. Restart Expo servers (Ctrl+C then npx expo start --tunnel)
echo   2. Scan QR codes with Expo Go
echo   3. Mobile apps will connect via ngrok tunnel
echo ===================================================
echo.
echo Press any key to open ngrok dashboard...
pause > nul
start http://localhost:4040
