@echo off
title Ngrok Multi-Tunnel (All Endpoints)
color 0B

echo.
echo ===================================================
echo   NGROK MULTI-TUNNEL SETUP
echo   Exposes: Backend (8000) + Advertiser (8081) + Receiver (8082)
echo ===================================================
echo.

set NGROK_PATH=%~dp0ngrok.exe

if not exist "%NGROK_PATH%" (
    echo [ERROR] ngrok.exe not found at: %NGROK_PATH%
    echo.
    echo Download ngrok from https://ngrok.com/download
    pause
    exit /b 1
)

echo [1/4] Found ngrok at: %NGROK_PATH%
echo.

REM Check if authtoken is configured
echo [2/4] Checking ngrok auth...
"%NGROK_PATH%" config check >nul 2>&1
if errorlevel 1 (
    echo [WARNING] ngrok may not be authenticated.
    echo Run: ngrok config add-authtoken YOUR_TOKEN
    echo Get token from: https://dashboard.ngrok.com/get-started/your-authtoken
    echo.
)

echo [3/4] Starting ALL tunnels (backend + mobile apps + frontend)...
echo.
echo This will create 4 public URLs:
echo   - Backend API (port 8000)
echo   - BLE Advertiser (port 8081)
echo   - BLE Receiver (port 8082)
echo   - Frontend Dashboard (port 5173)
echo.

REM Start ngrok with all tunnels using config file
REM Start ngrok with all tunnels using config file
start "Ngrok Tunnels" cmd /k ""%NGROK_PATH%" start --all --config "%~dp0ngrok.yml""

echo [4/4] Waiting for tunnels to initialize (8 seconds)...
timeout /t 8 /nobreak > nul

echo.
echo ===================================================
echo   FETCHING PUBLIC URLs
echo ===================================================
echo.

REM Query ngrok API to get all tunnel URLs
powershell -Command ^
    "$tunnels = (Invoke-RestMethod -Uri 'http://localhost:4040/api/tunnels').tunnels; " ^
    "foreach ($t in $tunnels) { " ^
    "    Write-Host ('  ' + $t.name + ': ' + $t.public_url) -ForegroundColor Cyan " ^
    "}"

echo.

REM Also update mobile config files with the backend URL
for /f "tokens=*" %%i in ('powershell -Command "(Invoke-RestMethod -Uri 'http://localhost:4040/api/tunnels').tunnels | Where-Object { $_.config.addr -match ':8000' } | Select-Object -First 1 -ExpandProperty public_url"') do set BACKEND_URL=%%i

if not "%BACKEND_URL%"=="" (
    echo.
    echo [SUCCESS] Backend URL: %BACKEND_URL%
    echo.
    
    REM Update mobile config files
    (
    echo // Backend configuration for BLE Advertiser
    echo // This file is auto-generated by start_multi_tunnel.cmd
    echo // DO NOT EDIT MANUALLY - it will be overwritten
    echo.
    echo // Ngrok public URL - auto-updated
    echo export const BACKEND_URL = '%BACKEND_URL%';
    echo.
    echo // WebSocket URL ^(derived from BACKEND_URL^)
    echo export const WS_URL = BACKEND_URL.replace^('http', 'ws'^).replace^('https', 'wss'^) + '/ws';
    ) > "%~dp0mobile\ble-advertiser\config.ts"

    (
    echo // Backend configuration for BLE Receiver
    echo // This file is auto-generated by start_multi_tunnel.cmd
    echo // DO NOT EDIT MANUALLY - it will be overwritten
    echo.
    echo // Ngrok public URL - auto-updated
    echo export const BACKEND_URL = '%BACKEND_URL%';
    echo.
    echo // WebSocket URL ^(derived from BACKEND_URL^)
    echo export const WS_URL = BACKEND_URL.replace^('http', 'ws'^).replace^('https', 'wss'^) + '/ws';
    ) > "%~dp0mobile\ble-receiver\config.ts"
    
    echo [SUCCESS] Mobile config files updated!
) else (
    echo [WARNING] Could not fetch backend URL. Mobile configs not updated.
)

echo.
echo ===================================================
echo   ALL TUNNELS ACTIVE
echo ===================================================
echo.
echo Share these URLs with your friend:
echo   1. Backend API - for testing
echo   2. Advertiser/Receiver - for Expo Go
echo   3. Frontend Dashboard - for viewing the map/graphs
echo.
echo Ngrok Inspector: http://127.0.0.1:4040
echo.
echo Press any key to open ngrok inspector...
pause > nul
start http://127.0.0.1:4040/inspect/http
