@echo off
title Intent-Driven ATSC 3.0 - FULL DEMO LAUNCHER
color 0A

echo.
echo =====================================================================
echo     INTENT-DRIVEN ATSC 3.0 NETWORK SLICING
echo     FULL DEMO STACK LAUNCHER (total.cmd)
echo     ITU-T FG-AINN Build-a-thon 4.0
echo =====================================================================
echo.

REM Store the project directory
set PROJECT_DIR=%~dp0
set NGROK_PATH=%PROJECT_DIR%ngrok.exe

REM =====================================================================
REM STEP 1: Start Backend (FastAPI)
REM =====================================================================
echo [1/6] Starting Backend (FastAPI on port 8000)...
start "ATSC Backend" cmd /k "cd /d "%PROJECT_DIR%" && call venv\Scripts\activate && python -m uvicorn backend.main:app --reload --host 0.0.0.0 --port 8000"

echo       Waiting 8 seconds for backend to initialize...
timeout /t 8 /nobreak > nul

REM =====================================================================
REM STEP 2: Start Frontend (Vite)
REM =====================================================================
echo [2/6] Starting Frontend (Vite on port 5173)...
start "ATSC Frontend" cmd /k "cd /d "%PROJECT_DIR%frontend" && npm run dev"

echo       Waiting 5 seconds for frontend to initialize...
timeout /t 5 /nobreak > nul

REM =====================================================================
REM STEP 3: Start Ngrok Tunnel
REM =====================================================================
echo [3/6] Starting Ngrok tunnel for backend...

if not exist "%NGROK_PATH%" (
    echo [ERROR] ngrok.exe not found at: %NGROK_PATH%
    pause
    exit /b 1
)

REM Start ngrok in background
start /B "" "%NGROK_PATH%" http 8000 > nul 2>&1

echo       Waiting 6 seconds for ngrok to initialize...
timeout /t 6 /nobreak > nul

REM =====================================================================
REM STEP 4: Fetch Ngrok URL and Update Configs
REM =====================================================================
echo [4/6] Fetching ngrok public URL and updating mobile configs...

for /f "tokens=*" %%i in ('powershell -Command "(Invoke-RestMethod -Uri 'http://localhost:4040/api/tunnels').tunnels[0].public_url"') do set NGROK_URL=%%i

if "%NGROK_URL%"=="" (
    echo [WARNING] Failed to get ngrok URL. Using local IP fallback.
    set NGROK_URL=http://192.168.1.40:8000
)

echo       Ngrok URL: %NGROK_URL%

REM Update BLE Advertiser config
(
echo // Backend configuration for BLE Advertiser
echo // Auto-generated by total.cmd - DO NOT EDIT
echo.
echo export const BACKEND_URL = '%NGROK_URL%';
echo export const WS_URL = BACKEND_URL.replace^('http', 'ws'^).replace^('https', 'wss'^) + '/ws';
) > "%PROJECT_DIR%mobile\ble-advertiser\config.ts"

REM Update BLE Receiver config
(
echo // Backend configuration for BLE Receiver
echo // Auto-generated by total.cmd - DO NOT EDIT
echo.
echo export const BACKEND_URL = '%NGROK_URL%';
echo export const WS_URL = BACKEND_URL.replace^('http', 'ws'^).replace^('https', 'wss'^) + '/ws';
) > "%PROJECT_DIR%mobile\ble-receiver\config.ts"

echo       Config files updated!

REM =====================================================================
REM STEP 5: Start BLE Advertiser (Expo)
REM =====================================================================
echo [5/6] Starting BLE Advertiser (Expo)...
start "BLE Advertiser" cmd /k "cd /d "%PROJECT_DIR%mobile\ble-advertiser" && title BLE Advertiser - Scan QR with Expo Go && npx expo start --tunnel --port 8081"

echo       Waiting 5 seconds...
timeout /t 5 /nobreak > nul

REM =====================================================================
REM STEP 6: Start BLE Receiver (Expo)
REM =====================================================================
echo [6/6] Starting BLE Receiver (Expo)...
start "BLE Receiver" cmd /k "cd /d "%PROJECT_DIR%mobile\ble-receiver" && title BLE Receiver - Scan QR with Expo Go && npx expo start --tunnel --port 8082"

REM =====================================================================
REM DONE - Show Summary
REM =====================================================================
echo.
echo =====================================================================
echo   ALL SERVICES STARTED SUCCESSFULLY!
echo =====================================================================
echo.
echo   WINDOWS OPENED:
echo   [1] Backend       - http://localhost:8000
echo   [2] Frontend      - http://localhost:5173
echo   [3] BLE Advertiser - Scan QR with Expo Go (Phone 1)
echo   [4] BLE Receiver   - Scan QR with Expo Go (Phone 2)
echo.
echo   NGROK TUNNEL:
echo   %NGROK_URL%
echo.
echo =====================================================================
echo   DEMO FLOW:
echo   1. Open Frontend at http://localhost:5173
echo   2. Click "Quick Demo Mode" button in sidebar
echo   3. Open Advertiser on Phone 1 (scan QR)
echo   4. Open Receiver on Phone 2 (scan QR)
echo   5. Watch the constellation diagram and AI decisions!
echo =====================================================================
echo.
echo Press any key to open Frontend in browser...
pause > nul
start http://localhost:5173
