// Backend configuration for mobile apps
// This file is auto-generated by start_ngrok.cmd
// DO NOT EDIT MANUALLY - it will be overwritten

// When ngrok is running, this will be updated to the ngrok public URL
// When running locally, use your machine's local IP
export const BACKEND_URL = 'http://192.168.1.40:8000';

// WebSocket URL (derived from BACKEND_URL)
export const WS_URL = BACKEND_URL.replace('http', 'ws') + '/ws';
