import random
from typing import List, Dict

# Parameters for emergency alert traffic simulation
# In ATSC 3.0, emergency alerts are broadcast repeatedly to ensure reliability.
# This module provides a simple stress test generator.

def generate_emergency_alerts(duration_seconds: int = 60, interval_seconds: float = 0.5) -> List[Dict[str, float]]:
    """Generate a list of timestamps (in seconds) when emergency alerts are transmitted.

    Args:
        duration_seconds: Total simulation duration.
        interval_seconds: Desired interval between consecutive alerts (default 0.5 s).

    Returns:
        List of dicts with ``time`` key indicating when an alert is sent.
    """
    times = []
    t = 0.0
    while t < duration_seconds:
        times.append({"time": t})
        # Add jitter to simulate realistic transmission timing variations
        t += interval_seconds + random.uniform(-0.05, 0.05)
    return times

def compute_alert_reliability(success_rate_per_tx: float, alerts: List[Dict[str, float]]) -> float:
    """Estimate overall emergency alert delivery reliability.

    The model assumes independent success probability for each transmission.
    Reliability is the probability that at least one of the repeated alerts is received.

    Args:
        success_rate_per_tx: Probability that a single alert transmission is successfully received.
        alerts: List of alert transmission events (generated by ``generate_emergency_alerts``).

    Returns:
        Overall reliability (0.0‑1.0).
    """
    if not alerts:
        return 0.0
    # Probability that none of the alerts succeed
    fail_prob = (1 - success_rate_per_tx) ** len(alerts)
    return 1 - fail_prob

# Example usage (for debugging)
if __name__ == "__main__":
    alerts = generate_emergency_alerts()
    reliability = compute_alert_reliability(0.9, alerts)
    print(f"Generated {len(alerts)} alerts, estimated reliability: {reliability:.4f}")
