// Backend configuration for BLE Advertiser
// This file is auto-generated by start_ngrok.cmd
// DO NOT EDIT MANUALLY - it will be overwritten

// Ngrok public URL - auto-updated
export const BACKEND_URL = 'https://felicita-savoriest-nonmeteorologically.ngrok-free.dev';

// WebSocket URL (derived from BACKEND_URL)
export const WS_URL = BACKEND_URL.replace('http', 'ws').replace('https', 'wss') + '/ws';
